### ISSUE TITLE
Test breaks on windows when upgrading Python 3.9->3.12

### ISSUE THREAD

**Issue by mih** [datalad/datasalad#44] opened 2024-09-22 15:55 UTC
Demo: https://github.com/datalad/datasalad/pull/43

@christian-monch do you have an idea what might go wrong?

**Comment by christian-monch** [comment] 2024-09-25 08:10
I could not reproduce the error, and it no longer shows up on CI. I am closing this issue.

**Closed by christian-monch** 2024-09-25 08:10 UTC
